#!/bin/bash



if (( $# == 0 )); then
	# Msg
	echo "--------------------------------------------------";
	echo "";
	echo "USAGE     : newclass <className>";
	echo "EXAMPLE   : newclass 'TheDate'         -> Creates new class 'TheDate' in ./src/ (skipped if class exists)";
	echo "";
	echo "--------------------------------------------------";
	exit;
elif (( $# == 1 )); then
	# Set names width case
	xxxxx=$(echo $1 | sed -re "s/^(.*)/\L\1/g");
	XXXXX=$(echo $1 | sed -re "s/^(.*)/\U\1/g");
	Xxxxx=$(echo $1 | sed -re "s/^(.)(.*)/\U\1\L\2/g");
	XxXxx=$(echo $1 | sed -re "s/^(.)/\U\1/g");
	xxXxx=$(echo $1 | sed -re "s/^(.)/\L\1/g");

	# If class does not exist
	if [ ! -f "./src/$xxxxx.h" ] && [ ! -f "./src/$xxxxx.cpp" ]; then
		# Create .h and .cpp files from template
		cat ./.template/xxxxx.h | sed -re "s/xxxxx/$xxxxx/g" | sed -re "s/XXXXX/$XXXXX/g" | sed -re "s/Xxxxx/$Xxxxx/g" | sed -re "s/XxXxx/$XxXxx/g" | sed -re "s/xxXxx/$xxXxx/g" > ./src/$xxxxx.h;
		cat ./.template/xxxxx.cpp | sed -re "s/xxxxx/$xxxxx/g" | sed -re "s/XXXXX/$XXXXX/g" | sed -re "s/Xxxxx/$Xxxxx/g" | sed -re "s/XxXxx/$XxXxx/g" | sed -re "s/xxXxx/$xxXxx/g" > ./src/$xxxxx.cpp;

		# Open with atom
		atom ./src/$xxxxx.h;
		atom ./src/$xxxxx.cpp;
	else
		echo -e "\t[FAIL] Class $XxXxx already exists";
	fi
fi
