#!/bin/bash



if (( $# == 0 )); then
	# Msg
	echo "--------------------------------------------------";
	echo "";
	echo "USAGE     : newprgm <prgmName>";
	echo "EXAMPLE   : newprgm 'prgm'             -> Creates new prgm 'prgm' in ./src/ (skipped if already exists)";
	echo "";
	echo "--------------------------------------------------";
	exit;
elif (( $# == 1 )); then
	# Set names width case
	xxxxx=$(echo $1 | sed -re "s/(.*)/\L\1/g");

	# If prgm does not exist
	if [ ! -f "./src/$xxxxx.cpp" ]; then
		# Create prgm
		cp ./.template/prgm.cpp ./src/$xxxxx.cpp;

		# Open with atom
		atom ./src/$xxxxx.cpp;
	else
		echo -e "\t[FAIL] Prgm $xxxxx.cpp already exists";
	fi

	# If utils library does not exist
	if [ ! -f "./src/utils.h" ] && [ ! -f "./src/utils.cpp" ]; then
		# Create prgm
		cp ./.template/utils.h ./src/utils.h;
		cp ./.template/utils.cpp ./src/utils.cpp;
	else
		echo -e "\t[FAIL] Utils library already exists";
	fi
fi
